---
services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    networks:
      - inception_net
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  redis:
    build: ./requirements/bonus/redis/
    container_name: redis
    networks:
      - inception_net
    restart: always
  wordpress:
    build: ./requirements/bonus/wordpress/
    container_name: wordpress
    networks:
      - inception_net
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    networks:
      - inception_net
    ports:
      - "3443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
  vsftpd:
    build: ./requirements/bonus/vsftpd/
    container_name: vsftpd
    networks:
      - inception_net
    ports:
      - "3021:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/home/vsftpd
    depends_on:
      - wordpress
    restart: always
  thursday:
    build: ./requirements/bonus/thursday/
    container_name: thursday
    ports:
      - "3000:80"
    restart: always
  adminer:
    build: ./requirements/bonus/adminer/
    container_name: adminer
    networks:
    - inception_net
    ports:
      - "8080:8080"
    restart: always
  portainer:
    build: ./requirements/bonus/portainer/
    container_name: portainer
    networks:
      - inception_net
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/anbaya/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/anbaya/data/wordpress
  portainer_data:
    driver: local
networks:
  inception_net:
    driver: bridge